spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        # Put here your user name
        username: root
        # Put here your password
        password: 'Weak'
        url: jdbc:mysql://localhost:3306/mobilele_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    jpa:
        #For MySQL 8 uncomment bellow (comment MySQL 5)
        #database-platform: org.hibernate.dialect.MySQL8Dialect
        #For MySQL 5 (innodb dialect below)
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

server:
    port: 8081
